# Generated by Django 3.2.3 on 2021-05-31 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MapIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=20)),
                ('image', models.ImageField(height_field=30, upload_to='core/images', width_field=30)),
                ('game_item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameitem', verbose_name='Game item')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameitem', verbose_name='Game item')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('expected_answer', models.BooleanField(verbose_name='True')),
                ('quiz_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz', verbose_name='Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='MapIconQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer_message', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=300)),
                ('incorrect_answer', models.CharField(max_length=300)),
                ('map_icon_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mapicon', verbose_name='Icon')),
            ],
        ),
    ]
