# Generated by Django 3.2.3 on 2021-05-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapicon',
            name='image',
            field=models.ImageField(height_field='30', upload_to='core/images', width_field='30'),
        ),
    ]
