# Generated by Django 3.2.3 on 2021-05-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_wheeloffortune_wheeloffortuneitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WheelOfFortuneItem',
            new_name='Item',
        ),
    ]
