# Generated by Django 3.2.3 on 2021-05-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_wheeloffortuneitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mophene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MorpheneWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('morphene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mophene')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morphenes', models.ManyToManyField(through='game.MorpheneWord', to='game.Mophene')),
            ],
        ),
        migrations.RemoveField(
            model_name='map',
            name='wheel_fk',
        ),
        migrations.RemoveField(
            model_name='mapquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='mapquestion',
            name='map_fk',
        ),
        migrations.RemoveField(
            model_name='mapquestionanswer',
            name='map_question_fk',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='wheel_fk',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='MapQuestion',
        ),
        migrations.DeleteModel(
            name='MapQuestionAnswer',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AddField(
            model_name='sentenceword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.word'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='words',
            field=models.ManyToManyField(through='game.SentenceWord', to='game.Word'),
        ),
        migrations.AddField(
            model_name='morpheneword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.word'),
        ),
    ]
