# Generated by Django 3.2.3 on 2021-05-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210521_1326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='GameItem',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='wheel_fk',
            new_name='game_item_fk',
        ),
    ]
