# Generated by Django 3.2.3 on 2021-05-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210521_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='expected_answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='game_item_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameitem', verbose_name='Game item'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300, verbose_name='True/false')),
                ('quiz_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz', verbose_name='Quiz')),
            ],
        ),
    ]
