# Generated by Django 3.2.3 on 2021-05-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20210521_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(max_length=20)),
                ('game_item_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameitem', verbose_name='Game item')),
            ],
        ),
        migrations.CreateModel(
            name='MapIconQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer_message', models.CharField(max_length=300)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mapquestionanswer')),
                ('map_icon_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mapicon', verbose_name='Icon')),
            ],
        ),
        migrations.RemoveField(
            model_name='mapquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='mapquestion',
            name='map_fk',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.AlterField(
            model_name='mapquestionanswer',
            name='map_question_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.mapiconquestion'),
        ),
        migrations.DeleteModel(
            name='MapQuestion',
        ),
    ]
