# Generated by Django 3.2.3 on 2021-05-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20210521_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapiconquestion',
            name='incorrect_answer',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mapiconquestion',
            name='correct_answer',
            field=models.CharField(max_length=300),
        ),
    ]
