export const QUESTIONS_LOADED = "QUESTIONS_LOADED";
export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const CLEAR_QUESTIONS = "CLEAR_QUESTIONS";

export const SET_GAME_OBJECT = "SET_GAME_OBJECT";
export const CLEAR_GAME_OBJECT = "CLEAR_GAME_OBJECT";

export const SET_HTTP_LOADING = "SET_HTTP_LOADING";
export const SET_HTTP_INACTIVE = "SET_HTTP_INACTIVE";

export const START_GAME = "START_GAME";
export const END_GAME = "END_GAME";
export const RESTART_GAME = "RESTART_GAME";
export const SWITCH_STAGE = "SWITCH_STAGE";
export const EXIT_GAME = "EXIT_GAME";

export const SET_POINTS = "SET_POINTS";

export const REMOVE_SECTOR = "REMOVE_SECTOR";

export const MAP_QUESTIONS_LOADING = "MAP_QUESTIONS_LOADING";
export const MAP_QUESTIONS_LOADED = "MAP_QUESTIONS_LOADED";
export const SET_MAP_QUESTIONS = "SET_MAP_QUESTIONS";

export const PLAY_TRANSITION = "PLAY_TRANSITION";
export const STOP_TRANSITION = "STOP_TRANSITION";
